document.writeln("<link href=\'http://www.jmqx.gov.cn/ScrollPic2.css\' rel=\'stylesheet\' type=\'text/css\'>");
document.writeln("<script type=\'text/javascript\' src=\'http://www.jmqx.gov.cn/js/jquery-1.6.4.min.js\'></script>");
document.writeln("<script src=\'http://www.jmqx.gov.cn/Js/jquery.litenav.js\' type=\'text/javascript\'></script>");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("       $(function(){");
document.writeln("       $(\'#hotpic\').liteNav(1000);");
document.writeln("       })");
document.writeln("</script>");
document.writeln("<link href=\'http://www.cpc.ncep.noaa.gov/nwscwi/main.css\' type=\'text/css\' rel=\'STYLESHEET\'>");
document.writeln("");
