document.writeln("<meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge,chrome=1\'> ");
document.writeln("<meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'swipe/css/normalize.css\' />");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'swipe/css/default.css\'>");
document.writeln("<link rel=\'stylesheet\' href=\'swipe/dist/photoswipe.css\'> ");
document.writeln("<link rel=\'stylesheet\' href=\'swipe/dist/default-skin/default-skin.css\'> ");
document.writeln("<link rel=\'stylesheet\' href=\'swipe/css/site.css\'> ");
document.writeln("<!-- Core JS file -->");
document.writeln("<script src=\'swipe/dist/photoswipe.min.js\'></script> ");
document.writeln("<!-- UI JS file -->");
document.writeln("<script src=\'swipe/dist/photoswipe-ui-default.min.js\'></script> ");
document.writeln("<style type=\'text/css\'>");
document.writeln("</style>");
document.writeln("<!--[if IE]>");
document.writeln("  <script src=\'swipe/dist/photoswipe-ui-default.min.js\'></script>");
document.writeln("<![endif]-->");
