document.writeln("<script src=\'https://weatherpat.github.io/weather/js/photoswipe.js\'></script>");
document.writeln("<div class=\'row\'>");
document.writeln(" <div id=\'demo-test-gallery\' class=\'demo-gallery\'>");
document.writeln("  <a href=\'http://andrew.rsmas.miami.edu/bmcnoldy/tropics/atcf/latestGLOBE.png\' data-size=\'2000x798\' data-med=\'http://andrew.rsmas.miami.edu/bmcnoldy/tropics/atcf/latestNWP.png\' data-med-size=\'800x800\' data-author=\'andrew.rsmas.miami.edu\'>");
document.writeln("   <img src=\'http://andrew.rsmas.miami.edu/bmcnoldy/tropics/atcf/latestNWP.png\' alt=\'聯合臺風警報中心_全球擾亂\'>");
document.writeln("    <figure>全球擾亂(NHC and JTWC)...</figure></a>");
document.writeln("<!--  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/SettleImage_SZ_7.PNG\' data-size=\'1600x1196\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/SettleImage_SZ_7.PNG\' data-med-size=\'800x598\'  data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/SettleImage_SZ_7.PNG\' alt=\'每小時衛星紅外雲圖\'>");
document.writeln("    <figure>衛星紅外雲圖...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_Tempture_60分钟.png\' data-size=\'1600x1482\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_Tempture_60分钟.png\' data-med-size=\'800x741\' data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_Tempture_60分钟.png\' alt=\'每小時各區溫度圖\'>");
document.writeln("    <figure>溫度圖...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_WIND_60分钟.png\'  data-size=\'1600x1482\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_WIND_60分钟.png\' data-med-size=\'800x741\' data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_WIND_60分钟.png\' alt=\'每小時各區風向圖\'>");
document.writeln("    <figure>風向圖...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_RAINFALL_日雨量.png\'  data-size=\'1600x1482\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_RAINFALL_日雨量.png\' data-med-size=\'800x741\' data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_RAINFALL_日雨量.png\' alt=\'天累計雨量圖\'>");
document.writeln("    <figure>雨量圖...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_GD_CAPPI_7.PNG\' data-size=\'1600x1400\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_GD_CAPPI_7.PNG\' data-med-size=\'800x700\' data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_GD_CAPPI_7.PNG\' alt=\'2.5公裏高度雷達實況\'>");
document.writeln("    <figure>2.5公裏高度雷達實況...</figure></a>" -->);
document.writeln("  <a href=\'http://www.digital-typhoon.org/latest/globe/2048x2048/ir.jpg\' data-size=\'2048x2048\' data-med=\'http://agora.ex.nii.ac.jp/digital-typhoon/himawari-3g/latest/Hsfd/RGB/latest.jpg\' data-med-size=\'1000x1000\' data-author=\'digital-typhoon.org\'>");
document.writeln("   <img src=\'http://www.digital-typhoon.org/latest/globe/512x512/ir.jpg\' alt=\'Himawari-8_衛星雲圖\'>");
document.writeln("    <figure>Himawari-8_衛星雲圖...</figure></a>");
document.writeln("  <a href=\'http://www.metoc.navy.mil/jtwc/products/abpwsair.jpg\'  data-size=\'2100x1500\' data-med=\'http://www.metoc.navy.mil/jtwc/products/abpwsair.jpg\' data-med-size=\'800x571\' data-author=\'www.prh.onaa.gov/cphc/\'>");
document.writeln("   <img src=\'http://www.metoc.navy.mil/jtwc/products/abpwsair.jpg\' alt=\'Product of JTWC/SATOPS\'>");
document.writeln("    <figure>Product of JTWC/SATOPS...</figure></a>");
document.writeln(" </div>");
document.writeln("</div>");
document.writeln("<script src=\'https://weatherpat.github.io/weather/js/set_swipe.js\'></script>");
