document.writeln("<script src=\'https://weatherpat.github.io/weather/js/photoswipe.js\'></script>");
document.writeln("<div class=\'row\'>");
document.writeln(" <div id=\'demo-test-gallery\' class=\'demo-gallery\'>");
document.writeln("  <a href=\'https://metoc.ndbc.noaa.gov/ProductFeeds-portlet/img/jtwc/products/abpwsair.jpg\'  data-size=\'2100x1500\' data-med=\'https://metoc.ndbc.noaa.gov/ProductFeeds-portlet/img/jtwc/products/abpwsair.jpg\' data-med-size=\'800x571\' data-author=\'www.prh.onaa.gov/cphc/\'>");
document.writeln("   <img src=\'https://metoc.ndbc.noaa.gov/ProductFeeds-portlet/img/jtwc/products/abpwsair.jpg\' alt=\'Product of JTWC/SATOPS\'>");
document.writeln("    <figure>Product of JTWC/SATOPS...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/SettleImage_SZ_7.PNG\' data-size=\'1600x1196\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/SettleImage_SZ_7.PNG\' data-med-size=\'800x598\'  data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/SettleImage_SZ_7.PNG\' alt=\'每小時衛星紅外雲圖\'>");
document.writeln("    <figure>衛星紅外雲圖...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_Tempture_60分钟.png\' data-size=\'1600x1482\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_Tempture_60分钟.png\' data-med-size=\'800x741\' data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_Tempture_60分钟.png\' alt=\'每小時各區溫度圖\'>");
document.writeln("    <figure>溫度圖...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_WIND_60分钟.png\'  data-size=\'1600x1482\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_WIND_60分钟.png\' data-med-size=\'800x741\' data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_WIND_60分钟.png\' alt=\'每小時各區風向圖\'>");
document.writeln("    <figure>風向圖...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_RAINFALL_日雨量.png\'  data-size=\'1600x1482\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_RAINFALL_日雨量.png\' data-med-size=\'800x741\' data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_RAINFALL_日雨量.png\' alt=\'天累計雨量圖\'>");
document.writeln("    <figure>雨量圖...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_GD_CAPPI_7.PNG\' data-size=\'1600x1400\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_GD_CAPPI_7.PNG\' data-med-size=\'800x700\' data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_GD_CAPPI_7.PNG\' alt=\'2.5公裏高度雷達實況\'>");
document.writeln("    <figure>2.5公裏高度雷達實況...</figure></a>");
document.writeln(" </div>");
document.writeln("</div>");
document.writeln("<script src=\'https://weatherpat.github.io/weather/js/set_swipe.js\'></script>");