document.writeln("<script src=\'https://weatherpat.github.io/weather/js/photoswipe.js\'></script>");
document.writeln("<div class=\'row\'>");
document.writeln(" <div id=\'demo-test-gallery\' class=\'demo-gallery\'>");
document.writeln("<!--  <a href=\'https://metoc.ndbc.noaa.gov/ProductFeeds-portlet/img/jtwc/products/abpwsair.jpg\'  data-size=\'2100x1500\' data-med=\'https://metoc.ndbc.noaa.gov/ProductFeeds-portlet/img/jtwc/products/abpwsair.jpg\' data-med-size=\'800x571\' data-author=\'www.prh.onaa.gov/cphc/\'>");
document.writeln("   <img src=\'https://metoc.ndbc.noaa.gov/ProductFeeds-portlet/img/jtwc/products/abpwsair.jpg\' alt=\'Product of JTWC/SATOPS\'>");
document.writeln("    <figure>Product of JTWC/SATOPS...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/SettleImage_SZ_7.PNG\' data-size=\'1600x1196\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/SettleImage_SZ_7.PNG\' data-med-size=\'800x598\'  data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/SettleImage_SZ_7.PNG\' alt=\'每小時衛星紅外雲圖\'>");
document.writeln("    <figure>衛星紅外雲圖...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_Tempture_60分钟.png\' data-size=\'1600x1482\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_Tempture_60分钟.png\' data-med-size=\'800x741\' data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_Tempture_60分钟.png\' alt=\'每小時各區溫度圖\'>");
document.writeln("    <figure>溫度圖...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_WIND_60分钟.png\'  data-size=\'1600x1482\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_WIND_60分钟.png\' data-med-size=\'800x741\' data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_WIND_60分钟.png\' alt=\'每小時各區風向圖\'>");
document.writeln("    <figure>風向圖...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_RAINFALL_日雨量.png\'  data-size=\'1600x1482\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_RAINFALL_日雨量.png\' data-med-size=\'800x741\' data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_SZ_RAINFALL_日雨量.png\' alt=\'天累計雨量圖\'>");
document.writeln("    <figure>雨量圖...</figure></a>");
document.writeln("  <a href=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_GD_CAPPI_7.PNG\' data-size=\'1600x1400\' data-med=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_GD_CAPPI_7.PNG\' data-med-size=\'800x700\' data-author=\'www.jmqx.gov.cn\'>");
document.writeln("   <img src=\'http://www.jmqx.gov.cn/upload/WeatherFiles/AWS_GD_CAPPI_7.PNG\' alt=\'2.5公裏高度雷達實況\'>");
document.writeln("    <figure>2.5公裏高度雷達實況...</figure></a> -->");
document.writeln("  <a href=\'http://tropic.ssec.wisc.edu/real-time/westpac/images/xxirgms5n.GIF\' data-size=\'1128x680\' data-med=\'http://tropic.ssec.wisc.edu/real-time/westpac/images/xxirgms5n.GIF\' data-med-size=\'800x482\' data-author=\'tropic.ssec.wisc.edu\'>");
document.writeln("   <img src=\'http://tropic.ssec.wisc.edu/real-time/westpac/images/xxirgms5n.GIF\' alt=\'西太平洋加強雲圖\'>");
document.writeln("    <figure>西太平洋加強雲圖...</figure></a>");
document.writeln("  <a href=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsvor.GIF\' data-size=\'1400x700\' data-med=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsvor.GIF\' data-med-size=\'800x400\' data-author=\'tropic.ssec.wisc.edu\'>");
document.writeln("   <img src=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsvor.GIF\' alt=\'西太平洋850HPA渦度\'>");
document.writeln("    <figure>西太平洋850HPA渦度...</figure></a>");
document.writeln("  <a href=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsconv.GIF\' data-size=\'1400x700\' data-med=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsconv.GIF\' data-med-size=\'800x400\' data-author=\'tropic.ssec.wisc.edu\'>");
document.writeln("   <img src=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsconv.GIF\' alt=\'西太平洋低空輻合\'>");
document.writeln("    <figure>西太平洋低空輻合...</figure></a>");
document.writeln("  <a href=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsdvg.GIF\' data-size=\'1400x700\' data-med=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsdvg.GIF\' data-med-size=\'800x400\' data-author=\'tropic.ssec.wisc.edu\'>");
document.writeln("   <img src=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsdvg.GIF\' alt=\'西太平洋高空輻散\'>");
document.writeln("    <figure>西太平洋高空輻散...</figure></a>");
document.writeln("  <a href=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsshr.GIF\' data-size=\'1400x700\' data-med=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsshr.GIF\' data-med-size=\'800x400\' data-author=\'tropic.ssec.wisc.edu\'>");
document.writeln("   <img src=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsshr.GIF\' alt=\'西太平洋垂直風切\'>");
document.writeln("    <figure>西太平洋垂直風切...</figure></a>");
document.writeln("  <a href=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmssht.GIF\' data-size=\'1400x700\' data-med=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmssht.GIF\' data-med-size=\'800x400\' data-author=\'tropic.ssec.wisc.edu\'>");
document.writeln("   <img src=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmssht.GIF\' alt=\'西太平洋垂直風切趨向\'>");
document.writeln("    <figure>西太平洋垂直風切趨向...</figure></a>");
document.writeln("  <a href=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmswv.GIF\' data-size=\'1400x700\' data-med=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmswv.GIF\' data-med-size=\'800x400\' data-author=\'tropic.ssec.wisc.edu\'>");
document.writeln("   <img src=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmswv.GIF\' alt=\'西太平洋高層風\'>");
document.writeln("    <figure>西太平洋高層風...</figure></a>");
document.writeln("  <a href=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsir.GIF\' data-size=\'1400x700\' data-med=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsir.GIF\' data-med-size=\'800x400\' data-author=\'tropic.ssec.wisc.edu\'>");
document.writeln("   <img src=\'http://tropic.ssec.wisc.edu/real-time/westpac/winds/wgmsir.GIF\' alt=\'西太平洋低層風\'>");
document.writeln("    <figure>西太平洋低層風...</figure></a>");
document.writeln("  <a href=\'http://www.digital-typhoon.org/latest/globe/2048x2048/ir.jpg\' data-size=\'2048x2048\' data-med=\'http://agora.ex.nii.ac.jp/digital-typhoon/himawari-3g/latest/Hsfd/RGB/latest.jpg\' data-med-size=\'1000x1000\' data-author=\'digital-typhoon.org\'>");
document.writeln("   <img src=\'http://www.digital-typhoon.org/latest/globe/512x512/ir.jpg\' alt=\'Himawari-8_衛星雲圖\'>");
document.writeln("    <figure>Himawari-8_衛星雲圖...</figure></a>");
document.writeln("  <a href=\'http://andrew.rsmas.miami.edu/bmcnoldy/tropics/atcf/latestGLOBE.png\' data-size=\'1050x419\' data-med=\'http://andrew.rsmas.miami.edu/bmcnoldy/tropics/atcf/latestNWP.png\' data-med-size=\'800x319\' data-author=\'andrew.rsmas.miami.edu\'>");
document.writeln("   <img src=\'http://andrew.rsmas.miami.edu/bmcnoldy/products.png\' alt=\'聯合臺風警報中心_全球擾亂\'>");
document.writeln("    <figure>全球擾亂(NHC and JTWC)...</figure></a>");
document.writeln("  <a href=\'https://www.tropicaltidbits.com/analysis/ocean/cdas-sflux_sst_wpac_1.png\' data-size=\'1024x717\' data-med=\'https://www.tropicaltidbits.com/analysis/ocean/cdas-sflux_sst_wpac_1.png\' data-med-size=\'800x560\' data-author=\'tropicaltidbits.com\'>");
document.writeln("   <img src=\'https://www.tropicaltidbits.com/analysis/ocean/cdas-sflux_sst_wpac_1.png\' alt=\'西太平洋海面溫度\'>");
document.writeln("    <figure>西太平洋海面溫度...</figure></a>");
document.writeln("  <a href=\'http://www.cpc.ncep.noaa.gov/products/precip/CWlink/MJO/ensplume_full.gif\' data-size=\'1024x1024\' data-med=\'http://www.cpc.ncep.noaa.gov/products/precip/CWlink/MJO/ensplume_full.gif\' data-med-size=\'800x800\' data-author=\'cpc.ncep.noaa.gov\'>");
document.writeln("   <img src=\'http://www.cpc.ncep.noaa.gov/products/precip/CWlink/MJO/ensplume_full.gif\' alt=\'MJO\'>");
document.writeln("    <figure>熱帶季節內振蕩(MJO)...</figure></a>");
document.writeln(" </div>");
document.writeln("</div>");
document.writeln("<script src=\'https://weatherpat.github.io/weather/js/set_swipe.js\'></script>");
