document.writeln("</br>");
document.writeln("<p id=\'time1\' style=\'color: blueviolet;\'></p>");
document.writeln("<script>");
document.writeln("function getCurDate()");
document.writeln("{");
document.writeln("var d = new Date();");
document.writeln("var years = d.getFullYear();");
document.writeln("var month = add_zero(d.getMonth()+1);");
document.writeln("var days = add_zero(d.getDate());");
document.writeln("var hours = add_zero(d.getHours());");
document.writeln("var minutes = add_zero(d.getMinutes());");
document.writeln("var seconds=add_zero(d.getSeconds());");
document.writeln("var ndate = \'當前系統時間(Sys_Time):\'+years+\'/\'+month+\'/\'+days+\' \'+hours+\':\'+minutes+\':\'+seconds;");
document.writeln("var divT=document.getElementById(\'time1\');");
document.writeln("divT.innerHTML= ndate;");
document.writeln("}");
document.writeln("function add_zero(temp)");
document.writeln("{");
document.writeln("if(temp<10) return \'0\'+temp;");
document.writeln("else return temp;");
document.writeln("}");
document.writeln("setInterval(\'getCurDate()\',100);");
document.writeln("</script>");

document.writeln("<p id=\'time2\'></p>");
document.writeln("<script>");
document.writeln("function mytime(){");
document.writeln("var today=new Date()");
document.writeln("var yyyy=today.getUTCFullYear()");
document.writeln("var mm=today.getUTCMonth()+1");
document.writeln("var dd=today.getUTCDate()");
document.writeln("var h=today.getUTCHours()");
document.writeln("var m=today.getUTCMinutes()");
document.writeln("var s=today.getUTCSeconds()");
document.writeln("var ms=today.getUTCMilliseconds()");
document.writeln("// add a zero in front of numbers<10");
document.writeln("mm=checkTime(mm)");
document.writeln("dd=checkTime(dd)");
document.writeln("m=checkTime(m)");
document.writeln("s=checkTime(s)");
document.writeln("document.getElementById(\'time2\').innerHTML=\'國際協調時間(UTC_Time):\'+yyyy+\'/\'+mm+\'/\'+dd+\' \'+h+\':\'+m+\':\'+s+\'.\'+ms");
document.writeln("");
document.writeln("");
document.writeln("        }");
document.writeln("  setInterval(function() {mytime()},1);  ");
document.writeln("function checkTime(i)");
document.writeln("{");
document.writeln("if (i<10) ");
document.writeln("  {i=\'0\' + i}");
document.writeln("  return i");
document.writeln("}");
document.writeln("</script>");
document.writeln("");

document.writeln("<p id=\'time3\'>");
document.writeln("<script language=\'Javascript\' src=\'http://time1909.beijing-time.org/time.asp\'></script>");
document.writeln("<script language=\'Javascript\' src=\'https://weatherpat.github.io/weather/js/setcalendar.js\'></script>");
document.writeln("中國北京時間:<font id=y></font>年<font id=m></font>月<font id=n></font>日　星期<font id=w></font>　農曆:<font id=nl></font>　<font id=hrs></font>:<font id=min></font>:<font id=sec></font>");
document.writeln("<script>");
document.writeln("writeday();Draw()");
document.writeln("</script>");
document.writeln("<script src=\'https://weatherpat.github.io/weather/js/Calendar.js\'></script>");
document.writeln("　<script type=\'text/javascript\'>document.write(getCalendar())</script>");
document.writeln("</br>");
